/*
 * Created on 29 Feb 2016 ( Time 17:46:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.ridas.bean.TblMembershipForm;
import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.bean.jpa.TblMembershipFormEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TblMembershipFormServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TblMembershipFormServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TblMembershipFormEntity' to 'TblMembershipForm'
	 * @param tblMembershipFormEntity
	 */
	public TblMembershipForm mapTblMembershipFormEntityToTblMembershipForm(TblMembershipFormEntity tblMembershipFormEntity) {
		if(tblMembershipFormEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TblMembershipForm tblMembershipForm = map(tblMembershipFormEntity, TblMembershipForm.class);

		//--- Link mapping ( link to TblMembershipForm )
		if(tblMembershipFormEntity.getTblMembershipForm() != null) {
			tblMembershipForm.setMemberFk(tblMembershipFormEntity.getTblMembershipForm().getMemberId());
		}
		return tblMembershipForm;
	}
	
	/**
	 * Mapping from 'TblMembershipForm' to 'TblMembershipFormEntity'
	 * @param tblMembershipForm
	 * @param tblMembershipFormEntity
	 */
	public void mapTblMembershipFormToTblMembershipFormEntity(TblMembershipForm tblMembershipForm, TblMembershipFormEntity tblMembershipFormEntity) {
		if(tblMembershipForm == null) {
			return;
		}

		//--- Generic mapping 
		map(tblMembershipForm, tblMembershipFormEntity);

		//--- Link mapping ( link : tblMembershipForm )
		if( hasLinkToTblMembershipForm(tblMembershipForm) ) {
			TblMembershipFormEntity tblMembershipForm1 = new TblMembershipFormEntity();
			tblMembershipForm1.setMemberId( tblMembershipForm.getMemberFk() );
			tblMembershipFormEntity.setTblMembershipForm( tblMembershipForm1 );
		} else {
			tblMembershipFormEntity.setTblMembershipForm( null );
		}

	}
	
	/**
	 * Verify that TblMembershipForm id is valid.
	 * @param TblMembershipForm TblMembershipForm
	 * @return boolean
	 */
	private boolean hasLinkToTblMembershipForm(TblMembershipForm tblMembershipForm) {
		if(tblMembershipForm.getMemberFk() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}