/*
 * Created on 29 Feb 2016 ( Time 17:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.ridas.bean.TblUserRoleMaster;
import com.ridas.bean.jpa.TblUserRoleMasterEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TblUserRoleMasterServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TblUserRoleMasterServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TblUserRoleMasterEntity' to 'TblUserRoleMaster'
	 * @param tblUserRoleMasterEntity
	 */
	public TblUserRoleMaster mapTblUserRoleMasterEntityToTblUserRoleMaster(TblUserRoleMasterEntity tblUserRoleMasterEntity) {
		if(tblUserRoleMasterEntity == null) {
			return null;
		}

		//--- Generic mapping 
		TblUserRoleMaster tblUserRoleMaster = map(tblUserRoleMasterEntity, TblUserRoleMaster.class);

		return tblUserRoleMaster;
	}
	
	/**
	 * Mapping from 'TblUserRoleMaster' to 'TblUserRoleMasterEntity'
	 * @param tblUserRoleMaster
	 * @param tblUserRoleMasterEntity
	 */
	public void mapTblUserRoleMasterToTblUserRoleMasterEntity(TblUserRoleMaster tblUserRoleMaster, TblUserRoleMasterEntity tblUserRoleMasterEntity) {
		if(tblUserRoleMaster == null) {
			return;
		}

		//--- Generic mapping 
		map(tblUserRoleMaster, tblUserRoleMasterEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}