/*
 * Created on 29 Feb 2016 ( Time 17:45:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.web.listitem;

import com.ridas.bean.TblMembershipForm;
import com.ridas.web.common.ListItem;

public class TblMembershipFormListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TblMembershipFormListItem(TblMembershipForm tblMembershipForm) {
		super();

		this.value = ""
			 + tblMembershipForm.getMemberId()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tblMembershipForm.getMemberName();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
