/*
 * Created on 29 Feb 2016 ( Time 17:45:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.web.listitem;

import com.ridas.bean.TblPlotMaster;
import com.ridas.web.common.ListItem;

public class TblPlotMasterListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TblPlotMasterListItem(TblPlotMaster tblPlotMaster) {
		super();

		this.value = ""
			 + tblPlotMaster.getPlotPk()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tblPlotMaster.getPlotNo();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
