/*
 * Created on 29 Feb 2016 ( Time 17:45:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.web.listitem;

import com.ridas.bean.TblUserMaster;
import com.ridas.web.common.ListItem;

public class TblUserMasterListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TblUserMasterListItem(TblUserMaster tblUserMaster) {
		super();

		this.value = ""
			 + tblUserMaster.getUserIdPk()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = tblUserMaster.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
