/*
 * Created on 29 Feb 2016 ( Time 17:46:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ridas.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.persistence.commons.jpa.GenericJpaService;
import com.ridas.persistence.commons.jpa.JpaOperation;
import com.ridas.persistence.services.TblMembershipFormPersistence;
import java.util.List;
import java.util.ArrayList;
import java.util.Date;
import com.ridas.web.common.CustomUserDetails;
import org.springframework.security.core.context.SecurityContextHolder;

//done as on 17 feb 2016 import the related entities too.
import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.bean.jpa.TblPlotMasterEntity;
import com.ridas.bean.jpa.TblReceiptMasterEntity;
import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.bean.TblBusiAssoMaster;
import com.ridas.bean.TblMembershipForm;
import com.ridas.bean.TblReceiptMaster;
import com.ridas.bean.jpa.TblBusiAssoMasterEntity;



/**
 * JPA implementation for basic persistence operations ( entity "TblMembershipForm" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblMembershipFormPersistenceJPA extends GenericJpaService<TblMembershipFormEntity, String> implements TblMembershipFormPersistence {

	/**
	 * Constructor
	 */
	public TblMembershipFormPersistenceJPA() {
		super(TblMembershipFormEntity.class);
	}

	@Override
	public TblMembershipFormEntity load( String memberId ) {
		return super.load( memberId );
	}

	@Override
	public boolean delete( String memberId ) {
	// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
		return deleteRelationships(memberId);

	}

	@Override
	public boolean delete(TblMembershipFormEntity entity) {
		if ( entity != null ) {
		// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
			return deleteRelationships(entity.getMemberId());
		}
		return false ;
	}

  /** done as on 17 feb 2016 delete the OnetoMany and OneToOne relations to dormant.
	*
	*/	
  private boolean deleteRelationships(final String pk)
  {
    JpaOperation operation = new JpaOperation() {
    @Override
   	public Object exectue(EntityManager em) throws PersistenceException {
    	final TblMembershipFormEntity entity = em.find(TblMembershipFormEntity.class, pk);
    	/*String entityname=TblSectorMasterEntity.class.getName();*/
    	entity.setStatus("dormant");
    	em.merge(entity);

		
 
		List<TblPlotMasterEntity> TblPlotMasterlist=entity.getListOfTblPlotMaster();
		for(int i=0;i<TblPlotMasterlist.size();i++)
		{
			TblPlotMasterEntity obj= TblPlotMasterlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 
		
 
		List<TblReceiptMasterEntity> TblReceiptMasterlist=entity.getListOfTblReceiptMaster();
		for(int i=0;i<TblReceiptMasterlist.size();i++)
		{
			TblReceiptMasterEntity obj= TblReceiptMasterlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 
		
 
		List<TblMembershipFormEntity> TblMembershipFormlist=entity.getListOfTblMembershipForm();
		for(int i=0;i<TblMembershipFormlist.size();i++)
		{
			TblMembershipFormEntity obj= TblMembershipFormlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 
		
 
		List<TblBusiAssoMasterEntity> TblBusiAssoMasterlist=entity.getListOfTblBusiAssoMaster();
		for(int i=0;i<TblBusiAssoMasterlist.size();i++)
		{
			TblBusiAssoMasterEntity obj= TblBusiAssoMasterlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 

	    if (entity!=null) {
    			 //em.remove(entity);
     			return Boolean.TRUE ;
    		}
    		else {
     			return Boolean.FALSE ;
    		}
   		}
	  } ;
	  // JPA operation execution 
	  Boolean b = (Boolean) execute(operation, true) ;
	  return b.booleanValue();
 	}


	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TblMembershipFormEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

 	/**
	 * Save the given entity ( TRANSACTIONAL )
	 * @param TblMembershipFormEntity
	 * 
	 * @return
	 */
	@Override
	public TblMembershipFormEntity save(final TblMembershipFormEntity entityToSave) {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {

				Boolean isnew=false;

//done as on 10 feb 2016 add condition to check if the table has auto increment if so hide the logic of manual key geenration.
				
//done as on 09 feb 2016 logic to check if this is an update or savenew call.
				if(entityToSave.getMemberId().equals("temp"))
				{
					isnew=true;
				
				}
				else
				{
					isnew=false;
				}	
				if(isnew==true)
				{
					TypedQuery<TblMembershipFormEntity> query = em.createQuery("select t from TblMembershipFormEntity t where t.countpk in (SELECT max(t2.countpk) from TblMembershipFormEntity t2)",TblMembershipFormEntity.class);
					TblMembershipFormEntity q=query.getSingleResult();
					Long maxpk=q.getCountpk();
					String prefix=q.getPrefixcolumn();
					++maxpk;
					String pkstring=prefix+maxpk;
//done as on 09 feb 2016 logic to check if the priamry is a string or numerical
					entityToSave.setMemberId(pkstring);
					entityToSave.setPrefixcolumn(prefix);
					entityToSave.setCountpk(maxpk);
					//done as on 16 feb 2016 to save create date on save 	
					 entityToSave.setCreateDate(new Date());
	
				}

				//done as on 16 feb 2016 to save create date on save
				entityToSave.setStatus("active");
	    		CustomUserDetails userDetails =
       				(CustomUserDetails)SecurityContextHolder.getContext().getAuthentication().getPrincipal();

				entityToSave.setUserId(userDetails.getUserid());

    			entityToSave.setModifiedDate(new Date());
			
				TblMembershipFormEntity managedEntity = em.merge(entityToSave);
				return managedEntity;
			}
		} ;
		// JPA operation execution 
		return (TblMembershipFormEntity) execute(operation, true) ;
	}
	
	
	
	@Override
	public List<TblMembershipFormEntity> findAllWhereClause() {
		
		
		
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				TypedQuery<TblMembershipFormEntity> query = em.createQuery("select DISTINCT t from TblMembershipFormEntity t ,TblPlotMasterEntity s where s.tblMembershipForm.memberId = t.memberId",TblMembershipFormEntity.class);
				return query.getResultList();
			}
		} ;
		// JPA operation execution 
		return (List<TblMembershipFormEntity>) execute(operation, true) ;
		
	}
/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
