/*
 * Created on 29 Feb 2016 ( Time 17:46:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ridas.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import com.ridas.bean.jpa.TblReceiptMasterEntity;
import com.ridas.persistence.commons.jpa.GenericJpaService;
import com.ridas.persistence.commons.jpa.JpaOperation;
import com.ridas.persistence.services.TblReceiptMasterPersistence;
import java.util.List;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Date;
import com.ridas.web.common.CustomUserDetails;

import org.hibernate.Session;
import org.hibernate.internal.SessionFactoryImpl;
import org.hibernate.service.jdbc.connections.spi.ConnectionProvider;
import org.springframework.security.core.context.SecurityContextHolder;

//done as on 17 feb 2016 import the related entities too.
import com.ridas.bean.jpa.TblBusiAssoMasterEntity;
import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.bean.jpa.TblPlotRecMasterEntity;



/**
 * JPA implementation for basic persistence operations ( entity "TblReceiptMaster" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblReceiptMasterPersistenceJPA extends GenericJpaService<TblReceiptMasterEntity, String> implements TblReceiptMasterPersistence {

	/**
	 * Constructor
	 */
	public TblReceiptMasterPersistenceJPA() {
		super(TblReceiptMasterEntity.class);
	}

	@Override
	public TblReceiptMasterEntity load( String receiptPk ) {
		return super.load( receiptPk );
	}

	@Override
	public boolean delete( String receiptPk ) {
	// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
		return deleteRelationships(receiptPk);

	}

	@Override
	public boolean delete(TblReceiptMasterEntity entity) {
		if ( entity != null ) {
		// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
			return deleteRelationships(entity.getReceiptPk());
		}
		return false ;
	}

  /** done as on 17 feb 2016 delete the OnetoMany and OneToOne relations to dormant.
	*
	*/	
  private boolean deleteRelationships(final String pk)
  {
    JpaOperation operation = new JpaOperation() {
    @Override
   	public Object exectue(EntityManager em) throws PersistenceException {
    	final TblReceiptMasterEntity entity = em.find(TblReceiptMasterEntity.class, pk);
    	/*String entityname=TblSectorMasterEntity.class.getName();*/
    	entity.setStatus("dormant");
    	em.merge(entity);

		
 
		List<TblBusiAssoMasterEntity> TblBusiAssoMasterlist=entity.getListOfTblBusiAssoMaster();
		for(int i=0;i<TblBusiAssoMasterlist.size();i++)
		{
			TblBusiAssoMasterEntity obj= TblBusiAssoMasterlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 
		
 
		List<TblPlotRecMasterEntity> TblPlotRecMasterlist=entity.getListOfTblPlotRecMaster();
		for(int i=0;i<TblPlotRecMasterlist.size();i++)
		{
			TblPlotRecMasterEntity obj= TblPlotRecMasterlist.get(i);
			obj.setStatus("dormant");
			em.merge(obj);
		}
 

	    if (entity!=null) {
    			 //em.remove(entity);
     			return Boolean.TRUE ;
    		}
    		else {
     			return Boolean.FALSE ;
    		}
   		}
	  } ;
	  // JPA operation execution 
	  Boolean b = (Boolean) execute(operation, true) ;
	  return b.booleanValue();
 	}


	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TblReceiptMasterEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

 	/**
	 * Save the given entity ( TRANSACTIONAL )
	 * @param TblReceiptMasterEntity
	 * 
	 * @return
	 */
	@Override
	public TblReceiptMasterEntity save(final TblReceiptMasterEntity entityToSave) {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {

				Boolean isnew=false;

//done as on 10 feb 2016 add condition to check if the table has auto increment if so hide the logic of manual key geenration.
				
//done as on 09 feb 2016 logic to check if this is an update or savenew call.
				if(entityToSave.getReceiptPk().equals("temp"))
				{
					isnew=true;
				
				}
				else
				{
					isnew=false;
				}	
				if(isnew==true)
				{
					TypedQuery<TblReceiptMasterEntity> query = em.createQuery("select t from TblReceiptMasterEntity t where t.countpk in (SELECT max(t2.countpk) from TblReceiptMasterEntity t2)",TblReceiptMasterEntity.class);
					TblReceiptMasterEntity q=query.getSingleResult();
					Long maxpk=q.getCountpk();
					String prefix=q.getPrefixcolumn();
					++maxpk;
					String pkstring=prefix+maxpk;
//done as on 09 feb 2016 logic to check if the priamry is a string or numerical
					entityToSave.setReceiptPk(pkstring);
					entityToSave.setPrefixcolumn(prefix);
					entityToSave.setCountpk(maxpk);
					//done as on 16 feb 2016 to save create date on save 	
					 entityToSave.setCreateDate(new Date());
	
				}

				//done as on 16 feb 2016 to save create date on save
				entityToSave.setStatus("active");
	    		CustomUserDetails userDetails =
       				(CustomUserDetails)SecurityContextHolder.getContext().getAuthentication().getPrincipal();

				entityToSave.setUserId(userDetails.getUserid());

    			entityToSave.setModifiedDate(new Date());
			
				TblReceiptMasterEntity managedEntity = em.merge(entityToSave);
				return managedEntity;
			}
		} ;
		// JPA operation execution 
		return (TblReceiptMasterEntity) execute(operation, true) ;
	}
	
	
	@Override
	public List<TblReceiptMasterEntity> findAllByRecType() {
		
		
		
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				TypedQuery<TblReceiptMasterEntity> query = em.createQuery("select DISTINCT s from TblReceiptMasterEntity s where s.receiptType = 'membership' AND status='active'",TblReceiptMasterEntity.class);
				return query.getResultList();
			}
		} ;
		// JPA operation execution 
		return (List<TblReceiptMasterEntity>) execute(operation, true) ;
		
	}
	public Connection connection;
	@Override
	public Connection myconnection(){
		JpaOperation operation = new JpaOperation() {
			

			@Override
			public Object exectue(EntityManager em) throws PersistenceException  {
				Session s = (Session) em.getDelegate();
				org.hibernate.SessionFactory sessionFactory=s.getSessionFactory();
				ConnectionProvider cp=((SessionFactoryImpl)sessionFactory).getConnectionProvider();
				try {
					 connection=cp.getConnection();
				} catch (SQLException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
				return null; 
			}
		} ;
		execute(operation);
		return connection;
		
	}
/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
