/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package com.ridas.persistence.services.jpa;


import javax.persistence.EntityManager;
import javax.persistence.PersistenceException;
import javax.persistence.Query;
import javax.persistence.TypedQuery;
import com.ridas.bean.jpa.TblUserRoleDetailsEntity;
import com.ridas.persistence.commons.jpa.GenericJpaService;
import com.ridas.persistence.commons.jpa.JpaOperation;
import com.ridas.persistence.services.TblUserRoleDetailsPersistence;
import java.util.List;
import java.util.Date;
import com.ridas.web.common.CustomUserDetails;
import org.springframework.security.core.context.SecurityContextHolder;

//done as on 17 feb 2016 import the related entities too.
import com.ridas.bean.jpa.TblUserRoleMasterEntity;
import com.ridas.bean.jpa.TblUserMasterEntity;



/**
 * JPA implementation for basic persistence operations ( entity "TblUserRoleDetails" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblUserRoleDetailsPersistenceJPA extends GenericJpaService<TblUserRoleDetailsEntity, String> implements TblUserRoleDetailsPersistence {

	/**
	 * Constructor
	 */
	public TblUserRoleDetailsPersistenceJPA() {
		super(TblUserRoleDetailsEntity.class);
	}

	@Override
	public TblUserRoleDetailsEntity load( String userRoleDetailId ) {
		return super.load( userRoleDetailId );
	}

	@Override
	public boolean delete( String userRoleDetailId ) {
	// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
		return deleteRelationships(userRoleDetailId);

	}

	@Override
	public boolean delete(TblUserRoleDetailsEntity entity) {
		if ( entity != null ) {
		// done as on 17 feb 2016 commented below logic of deleting to dormant by new method above for making the dormant fields for related entities
			return deleteRelationships(entity.getUserRoleDetailId());
		}
		return false ;
	}

  /** done as on 17 feb 2016 delete the OnetoMany and OneToOne relations to dormant.
	*
	*/	
  private boolean deleteRelationships(final String pk)
  {
    JpaOperation operation = new JpaOperation() {
    @Override
   	public Object exectue(EntityManager em) throws PersistenceException {
    	final TblUserRoleDetailsEntity entity = em.find(TblUserRoleDetailsEntity.class, pk);
    	/*String entityname=TblSectorMasterEntity.class.getName();*/
    	entity.setStatus("dormant");
    	em.merge(entity);


	    if (entity!=null) {
    			 //em.remove(entity);
     			return Boolean.TRUE ;
    		}
    		else {
     			return Boolean.FALSE ;
    		}
   		}
	  } ;
	  // JPA operation execution 
	  Boolean b = (Boolean) execute(operation, true) ;
	  return b.booleanValue();
 	}


	@Override
	public long countAll() {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {
				Query query = em.createNamedQuery("TblUserRoleDetailsEntity.countAll");
				return query.getSingleResult() ;
			}
		} ;
		// JPA operation execution 
		return (Long) execute(operation);
	}

 	/**
	 * Save the given entity ( TRANSACTIONAL )
	 * @param TblUserRoleDetailsEntity
	 * 
	 * @return
	 */
	@Override
	public TblUserRoleDetailsEntity save(final TblUserRoleDetailsEntity entityToSave) {
		// JPA operation definition 
		JpaOperation operation = new JpaOperation() {
			@Override
			public Object exectue(EntityManager em) throws PersistenceException {

				Boolean isnew=false;

//done as on 10 feb 2016 add condition to check if the table has auto increment if so hide the logic of manual key geenration.
				
//done as on 09 feb 2016 logic to check if this is an update or savenew call.
				if(entityToSave.getUserRoleDetailId().equals("temp"))
				{
					isnew=true;
				
				}
				else
				{
					isnew=false;
				}	
				if(isnew==true)
				{
					TypedQuery<TblUserRoleDetailsEntity> query = em.createQuery("select t from TblUserRoleDetailsEntity t where t.countpk in (SELECT max(t2.countpk) from TblUserRoleDetailsEntity t2)",TblUserRoleDetailsEntity.class);
					TblUserRoleDetailsEntity q=query.getSingleResult();
					Long maxpk=q.getCountpk();
					String prefix=q.getPrefixcolumn();
					++maxpk;
					String pkstring=prefix+maxpk;
//done as on 09 feb 2016 logic to check if the priamry is a string or numerical
					entityToSave.setUserRoleDetailId(pkstring);
					entityToSave.setPrefixcolumn(prefix);
					entityToSave.setCountpk(maxpk);
					//done as on 16 feb 2016 to save create date on save 	
					 entityToSave.setCreateDate(new Date());
	
				}

				//done as on 16 feb 2016 to save create date on save
				entityToSave.setStatus("active");
	    		CustomUserDetails userDetails =
       				(CustomUserDetails)SecurityContextHolder.getContext().getAuthentication().getPrincipal();

				entityToSave.setUserId(userDetails.getUserid());

    			entityToSave.setModifiedDate(new Date());
			
				TblUserRoleDetailsEntity managedEntity = em.merge(entityToSave);
				return managedEntity;
			}
		} ;
		// JPA operation execution 
		return (TblUserRoleDetailsEntity) execute(operation, true) ;
	}
/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
