/*
 * Created on 29 Feb 2016 ( Time 17:46:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services.fake;

import java.sql.Connection;
import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblBusiAssoMasterEntity;
import com.ridas.persistence.commons.fake.GenericFakeService;
import com.ridas.persistence.services.TblBusiAssoMasterPersistence;

/**
 * Fake persistence service implementation ( entity "TblBusiAssoMaster" )
 *
 * @author Telosys Tools Generator
 */
public class TblBusiAssoMasterPersistenceFAKE extends GenericFakeService<TblBusiAssoMasterEntity> implements TblBusiAssoMasterPersistence {

	public TblBusiAssoMasterPersistenceFAKE () {
		super(TblBusiAssoMasterEntity.class);
	}
	
	protected TblBusiAssoMasterEntity buildEntity(int index) {
		TblBusiAssoMasterEntity entity = new TblBusiAssoMasterEntity();
		// Init fields with mock values
		entity.setBuAsId( nextString() ) ;
		entity.setCountpk( nextLong() ) ;
		entity.setPrefixcolumn( nextString() ) ;
		entity.setCreateDate( nextDate() ) ;
		entity.setModifiedDate( nextDate() ) ;
		entity.setStatus( nextString() ) ;
		entity.setUserId( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(TblBusiAssoMasterEntity entity) {
		log("delete ( TblBusiAssoMasterEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String buAsId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TblBusiAssoMasterEntity entity) {
		log("insert ( TblBusiAssoMasterEntity : " + entity + ")" ) ;
	}

	public TblBusiAssoMasterEntity load( String buAsId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TblBusiAssoMasterEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TblBusiAssoMasterEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TblBusiAssoMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TblBusiAssoMasterEntity save(TblBusiAssoMasterEntity entity) {
		log("insert ( TblBusiAssoMasterEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TblBusiAssoMasterEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

	@Override
	public Connection myconnection() {
		// TODO Auto-generated method stub
		return null;
	}

/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
