/*
 * Created on 29 Feb 2016 ( Time 17:46:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblPlotRecMasterEntity;
import com.ridas.persistence.commons.fake.GenericFakeService;
import com.ridas.persistence.services.TblPlotRecMasterPersistence;

/**
 * Fake persistence service implementation ( entity "TblPlotRecMaster" )
 *
 * @author Telosys Tools Generator
 */
public class TblPlotRecMasterPersistenceFAKE extends GenericFakeService<TblPlotRecMasterEntity> implements TblPlotRecMasterPersistence {

	public TblPlotRecMasterPersistenceFAKE () {
		super(TblPlotRecMasterEntity.class);
	}
	
	protected TblPlotRecMasterEntity buildEntity(int index) {
		TblPlotRecMasterEntity entity = new TblPlotRecMasterEntity();
		// Init fields with mock values
		entity.setPlotReceiptId( nextInteger() ) ;
		entity.setCountpk( nextLong() ) ;
		entity.setPrefixcolumn( nextString() ) ;
		entity.setCreateDate( nextDate() ) ;
		entity.setModifiedDate( nextDate() ) ;
		entity.setStatus( nextString() ) ;
		entity.setUserId( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(TblPlotRecMasterEntity entity) {
		log("delete ( TblPlotRecMasterEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( Integer plotReceiptId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TblPlotRecMasterEntity entity) {
		log("insert ( TblPlotRecMasterEntity : " + entity + ")" ) ;
	}

	public TblPlotRecMasterEntity load( Integer plotReceiptId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TblPlotRecMasterEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TblPlotRecMasterEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TblPlotRecMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TblPlotRecMasterEntity save(TblPlotRecMasterEntity entity) {
		log("insert ( TblPlotRecMasterEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TblPlotRecMasterEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
