/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblUserMasterEntity;
import com.ridas.persistence.commons.fake.GenericFakeService;
import com.ridas.persistence.services.TblUserMasterPersistence;

/**
 * Fake persistence service implementation ( entity "TblUserMaster" )
 *
 * @author Telosys Tools Generator
 */
public class TblUserMasterPersistenceFAKE extends GenericFakeService<TblUserMasterEntity> implements TblUserMasterPersistence {

	public TblUserMasterPersistenceFAKE () {
		super(TblUserMasterEntity.class);
	}
	
	protected TblUserMasterEntity buildEntity(int index) {
		TblUserMasterEntity entity = new TblUserMasterEntity();
		// Init fields with mock values
		entity.setUserIdPk( nextString() ) ;
		entity.setUserName( nextString() ) ;
		entity.setUserPassword( nextString() ) ;
		entity.setUserAdmin( nextString() ) ;
		entity.setStatus( nextString() ) ;
		entity.setCreateDate( nextDate() ) ;
		entity.setModifiedDate( nextDate() ) ;
		entity.setPrefixcolumn( nextString() ) ;
		entity.setCountpk( nextLong() ) ;
		entity.setUserId( nextString() ) ;
		return entity ;
	}
	
	
	public boolean delete(TblUserMasterEntity entity) {
		log("delete ( TblUserMasterEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String userIdPk ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TblUserMasterEntity entity) {
		log("insert ( TblUserMasterEntity : " + entity + ")" ) ;
	}

	public TblUserMasterEntity load( String userIdPk ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TblUserMasterEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TblUserMasterEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TblUserMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TblUserMasterEntity save(TblUserMasterEntity entity) {
		log("insert ( TblUserMasterEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TblUserMasterEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
	 public List<TblUserMasterEntity> getUser(final String username)
	 {
		return null;
	 }
}
