/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services.fake;

import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblUserRoleMasterEntity;
import com.ridas.persistence.commons.fake.GenericFakeService;
import com.ridas.persistence.services.TblUserRoleMasterPersistence;

/**
 * Fake persistence service implementation ( entity "TblUserRoleMaster" )
 *
 * @author Telosys Tools Generator
 */
public class TblUserRoleMasterPersistenceFAKE extends GenericFakeService<TblUserRoleMasterEntity> implements TblUserRoleMasterPersistence {

	public TblUserRoleMasterPersistenceFAKE () {
		super(TblUserRoleMasterEntity.class);
	}
	
	protected TblUserRoleMasterEntity buildEntity(int index) {
		TblUserRoleMasterEntity entity = new TblUserRoleMasterEntity();
		// Init fields with mock values
		entity.setUserRoleId( nextString() ) ;
		entity.setUserRoleName( nextString() ) ;
		entity.setUserRoleModuleName( nextString() ) ;
		entity.setStatus( nextString() ) ;
		entity.setUserId( nextString() ) ;
		entity.setCreateDate( nextDate() ) ;
		entity.setModifiedDate( nextDate() ) ;
		entity.setPrefixcolumn( nextString() ) ;
		entity.setCountpk( nextLong() ) ;
		return entity ;
	}
	
	
	public boolean delete(TblUserRoleMasterEntity entity) {
		log("delete ( TblUserRoleMasterEntity : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( String userRoleId ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(TblUserRoleMasterEntity entity) {
		log("insert ( TblUserRoleMasterEntity : " + entity + ")" ) ;
	}

	public TblUserRoleMasterEntity load( String userRoleId ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<TblUserRoleMasterEntity> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<TblUserRoleMasterEntity> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<TblUserRoleMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public TblUserRoleMasterEntity save(TblUserRoleMasterEntity entity) {
		log("insert ( TblUserRoleMasterEntity : " + entity + ")" ) ;
		return entity;
	}

	public List<TblUserRoleMasterEntity> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

	@Override
	public long countAll() {
		return 0 ;
	}

/**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
