/*
 * Created on 18 Mar 2016 ( Time 11:55:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.ridas.bean.TblRtgsPaidDetails;

//done as on 19 feb 2016 introduced CSV Import logic
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
/**
 * Business Service Interface for entity TblRtgsPaidDetails.
 */
public interface TblRtgsPaidDetailsService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param rtgsDetailsId
	 * @return entity
	 */
	TblRtgsPaidDetails findById( Integer rtgsDetailsId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TblRtgsPaidDetails> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TblRtgsPaidDetails save(TblRtgsPaidDetails entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblRtgsPaidDetails update(TblRtgsPaidDetails entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblRtgsPaidDetails create(TblRtgsPaidDetails entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param rtgsDetailsId
	 */
	void delete( Integer rtgsDetailsId );

   /**
	* 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */

	/**
	 *	done as on 19 feb 2016 introduced CSV Import logic
	*/
	Boolean doImportExcelSpreadSheet(MultipartFile file) throws IOException;

	List findAllByProfit(Integer profit);

	String printRTGSReport(String profit, HttpServletRequest request, HttpServletResponse response);

	String printMonthlyRTGSReport(String profit, String month, String year, String paid, HttpServletRequest request,
			HttpServletResponse response);

	String printYearlyRTGSReport(List findAllByYear, HttpServletRequest request, HttpServletResponse response);

	
	String findAllByYear(String paramyear, HttpServletRequest request, HttpServletResponse response);

}
