/*
 * Created on 29 Feb 2016 ( Time 17:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import com.ridas.bean.TblReceiptMaster;

//done as on 19 feb 2016 introduced CSV Import logic
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
/**
 * Business Service Interface for entity TblReceiptMaster.
 */
public interface TblReceiptMasterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param receiptPk
	 * @return entity
	 */
	TblReceiptMaster findById( String receiptPk  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TblReceiptMaster> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TblReceiptMaster save(TblReceiptMaster entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblReceiptMaster update(TblReceiptMaster entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblReceiptMaster create(TblReceiptMaster entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param receiptPk
	 */
	void delete( String receiptPk );

   /**
	* 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */

	/**
	 *	done as on 19 feb 2016 introduced CSV Import logic
	*/
	Boolean doImportExcelSpreadSheet(MultipartFile file) throws IOException;

	List<TblReceiptMaster> findAllByRecType();

	String printPDFMembershipForm(String memberId, String param_chequenumber, String chequedateNew,
			String param_chequebank, String receiptPk, HttpServletRequest request, HttpServletResponse response);

	String printPDFReceipt(String receiptPk, HttpServletRequest request, HttpServletResponse response);

}
