/*
 * Created on 29 Feb 2016 ( Time 17:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service;

import java.util.List;

import com.ridas.bean.TblUserRoleMaster;

//done as on 19 feb 2016 introduced CSV Import logic
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
/**
 * Business Service Interface for entity TblUserRoleMaster.
 */
public interface TblUserRoleMasterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userRoleId
	 * @return entity
	 */
	TblUserRoleMaster findById( String userRoleId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TblUserRoleMaster> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TblUserRoleMaster save(TblUserRoleMaster entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblUserRoleMaster update(TblUserRoleMaster entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblUserRoleMaster create(TblUserRoleMaster entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userRoleId
	 */
	void delete( String userRoleId );

   /**
	* 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */

	/**
	 *	done as on 19 feb 2016 introduced CSV Import logic
	*/
	Boolean doImportExcelSpreadSheet(MultipartFile file) throws IOException;

}
