/*
 * Created on 29 Feb 2016 ( Time 17:46:21 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.business.service;

import java.util.List;

import com.ridas.bean.TblUserMaster;

//done as on 13 feb 2016 added below import to allow security of logging in.
import com.ridas.bean.jpa.TblUserMasterEntity;
//done as on 19 feb 2016 introduced CSV Import logic
import org.springframework.web.multipart.MultipartFile;
import java.io.IOException;
/**
 * Business Service Interface for entity TblUserMaster.
 */
public interface TblUserMasterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param userIdPk
	 * @return entity
	 */
	TblUserMaster findById( String userIdPk  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<TblUserMaster> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	TblUserMaster save(TblUserMaster entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblUserMaster update(TblUserMaster entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	TblUserMaster create(TblUserMaster entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param userIdPk
	 */
	void delete( String userIdPk );

   /**
	* 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
	  
 	List<TblUserMasterEntity> getUser(  String username);

	/**
	 *	done as on 19 feb 2016 introduced CSV Import logic
	*/
	Boolean doImportExcelSpreadSheet(MultipartFile file) throws IOException;

}
