/*
 * Created on 29 Feb 2016 ( Time 17:46:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.test.persistence;


import com.ridas.bean.jpa.TblPlotRecMasterEntity;
import com.ridas.mock.TblPlotRecMasterEntityMock;
import com.ridas.persistence.PersistenceServiceProvider;
import com.ridas.persistence.services.TblPlotRecMasterPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for TblPlotRecMaster persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblPlotRecMasterPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		TblPlotRecMasterPersistence service = PersistenceServiceProvider.getService(TblPlotRecMasterPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test TblPlotRecMaster persistence : delete + load ..." );
		
		TblPlotRecMasterPersistence service = PersistenceServiceProvider.getService(TblPlotRecMasterPersistence.class);
		
		TblPlotRecMasterEntityMock mock = new TblPlotRecMasterEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, 0  );
		// process( service, mock, ... );
	}

	private void process(TblPlotRecMasterPersistence service, TblPlotRecMasterEntityMock mock, Integer plotReceiptId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		TblPlotRecMasterEntity entity = service.load( plotReceiptId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( plotReceiptId ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . TblReceiptMaster
			// . TblPlotMaster
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( plotReceiptId );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
