/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.test.persistence;


import com.ridas.bean.jpa.TblUserRoleMasterEntity;
import com.ridas.mock.TblUserRoleMasterEntityMock;
import com.ridas.persistence.PersistenceServiceProvider;
import com.ridas.persistence.services.TblUserRoleMasterPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for TblUserRoleMaster persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblUserRoleMasterPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		TblUserRoleMasterPersistence service = PersistenceServiceProvider.getService(TblUserRoleMasterPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test TblUserRoleMaster persistence : delete + load ..." );
		
		TblUserRoleMasterPersistence service = PersistenceServiceProvider.getService(TblUserRoleMasterPersistence.class);
		
		TblUserRoleMasterEntityMock mock = new TblUserRoleMasterEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(TblUserRoleMasterPersistence service, TblUserRoleMasterEntityMock mock, String userRoleId ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		TblUserRoleMasterEntity entity = service.load( userRoleId );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( userRoleId ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( userRoleId );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
