/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.test.persistence;


import com.ridas.bean.jpa.TblUserMasterEntity;
import com.ridas.mock.TblUserMasterEntityMock;
import com.ridas.persistence.PersistenceServiceProvider;
import com.ridas.persistence.services.TblUserMasterPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for TblUserMaster persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class TblUserMasterPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test count ..." );
		
		TblUserMasterPersistence service = PersistenceServiceProvider.getService(TblUserMasterPersistence.class);
		System.out.println("CountAll = " + service.countAll() );
	}
	
	@Test
	public void test2() {
		
		System.out.println("Test TblUserMaster persistence : delete + load ..." );
		
		TblUserMasterPersistence service = PersistenceServiceProvider.getService(TblUserMasterPersistence.class);
		
		TblUserMasterEntityMock mock = new TblUserMasterEntityMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(TblUserMasterPersistence service, TblUserMasterEntityMock mock, String userIdPk ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		TblUserMasterEntity entity = service.load( userIdPk );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( userIdPk ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( userIdPk );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
