/*
 * Created on 29 Feb 2016 ( Time 17:46:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services;

import java.util.List;
import java.util.Map;

import com.ridas.bean.TblBusiAssoMaster;
import com.ridas.bean.TblMembershipForm;
import com.ridas.bean.jpa.TblMembershipFormEntity;

/**
 * Basic persistence operations for entity "TblMembershipForm"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface TblMembershipFormPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblMembershipForm
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(TblMembershipFormEntity tblMembershipForm) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param memberId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String memberId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblMembershipForm
	 */
	public void insert(TblMembershipFormEntity tblMembershipForm) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param memberId
	 * @return the entity loaded (or null if not found)
	 */
	public TblMembershipFormEntity load(String memberId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<TblMembershipFormEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<TblMembershipFormEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<TblMembershipFormEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblMembershipForm
	 * @return
	 */
	public TblMembershipFormEntity save(TblMembershipFormEntity tblMembershipForm) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<TblMembershipFormEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
    /**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */

	List<TblMembershipFormEntity> findAllWhereClause();

	
}
