/*
 * Created on 29 Feb 2016 ( Time 17:46:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services;

import java.sql.Connection;
import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblMembershipFormEntity;
import com.ridas.bean.jpa.TblReceiptMasterEntity;

/**
 * Basic persistence operations for entity "TblReceiptMaster"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface TblReceiptMasterPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblReceiptMaster
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(TblReceiptMasterEntity tblReceiptMaster) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param receiptPk
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String receiptPk) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblReceiptMaster
	 */
	public void insert(TblReceiptMasterEntity tblReceiptMaster) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param receiptPk
	 * @return the entity loaded (or null if not found)
	 */
	public TblReceiptMasterEntity load(String receiptPk) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<TblReceiptMasterEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<TblReceiptMasterEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<TblReceiptMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblReceiptMaster
	 * @return
	 */
	public TblReceiptMasterEntity save(TblReceiptMasterEntity tblReceiptMaster) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<TblReceiptMasterEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
    /**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */

	List<TblReceiptMasterEntity> findAllByRecType();

	Connection myconnection();
}
