/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services;

import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblUserRoleDetailsEntity;

/**
 * Basic persistence operations for entity "TblUserRoleDetails"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface TblUserRoleDetailsPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserRoleDetails
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(TblUserRoleDetailsEntity tblUserRoleDetails) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userRoleDetailId
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String userRoleDetailId) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserRoleDetails
	 */
	public void insert(TblUserRoleDetailsEntity tblUserRoleDetails) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param userRoleDetailId
	 * @return the entity loaded (or null if not found)
	 */
	public TblUserRoleDetailsEntity load(String userRoleDetailId) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<TblUserRoleDetailsEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<TblUserRoleDetailsEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<TblUserRoleDetailsEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserRoleDetails
	 * @return
	 */
	public TblUserRoleDetailsEntity save(TblUserRoleDetailsEntity tblUserRoleDetails) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<TblUserRoleDetailsEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
    /**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
}
