/*
 * Created on 29 Feb 2016 ( Time 17:46:07 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.persistence.services;

import java.util.List;
import java.util.Map;

import com.ridas.bean.jpa.TblUserMasterEntity;

/**
 * Basic persistence operations for entity "TblUserMaster"
 * 
 * This Bean has a basic Primary Key : String
 *
 * @author Telosys Tools Generator
 *
 */
public interface TblUserMasterPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserMaster
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(TblUserMasterEntity tblUserMaster) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param userIdPk
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(String userIdPk) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserMaster
	 */
	public void insert(TblUserMasterEntity tblUserMaster) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param userIdPk
	 * @return the entity loaded (or null if not found)
	 */
	public TblUserMasterEntity load(String userIdPk) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<TblUserMasterEntity> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<TblUserMasterEntity> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<TblUserMasterEntity> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param tblUserMaster
	 * @return
	 */
	public TblUserMasterEntity save(TblUserMasterEntity tblUserMaster) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<TblUserMasterEntity> search( Map<String, Object> criteria ) ;

	/**
	 * Count all the occurrences
	 * @return
	 */
	public long countAll();
    /**
	 * 	done as on 13 feb 2016 added for TblUserMaster for retrieving user details for login
    */
	 public List<TblUserMasterEntity> getUser(final String username);
}
