
/*
 * Created on 29 Feb 2016 ( Time 17:46:06 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.mock;

import java.util.LinkedList;
import java.util.List;

import com.ridas.bean.jpa.TblBusiAssoMasterEntity;
import com.ridas.mock.tool.MockValues;

public class TblBusiAssoMasterEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TblBusiAssoMasterEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(50) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TblBusiAssoMasterEntity createInstance( String buAsId ) {
		TblBusiAssoMasterEntity entity = new TblBusiAssoMasterEntity();
		// Init Primary Key fields
		entity.setBuAsId( buAsId) ;
		// Init Data fields
		entity.setCountpk( mockValues.nextLong() ) ; // java.lang.Long 
		entity.setPrefixcolumn( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setCreateDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setModifiedDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setStatus( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setUserId( mockValues.nextString(100) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setTblMembershipForm( TODO ) ; // TblMembershipForm 
		// setTblReceiptMaster( TODO ) ; // TblReceiptMaster 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TblBusiAssoMasterEntity> createList(int count) {
		List<TblBusiAssoMasterEntity> list = new LinkedList<TblBusiAssoMasterEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
