
/*
 * Created on 18 Mar 2016 ( Time 11:54:53 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.mock;

import java.util.LinkedList;
import java.util.List;

import com.ridas.bean.jpa.TblRtgsPaidDetailsEntity;
import com.ridas.mock.tool.MockValues;

public class TblRtgsPaidDetailsEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TblRtgsPaidDetailsEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TblRtgsPaidDetailsEntity createInstance( Integer rtgsDetailsId ) {
		TblRtgsPaidDetailsEntity entity = new TblRtgsPaidDetailsEntity();
		// Init Primary Key fields
		entity.setRtgsDetailsId( rtgsDetailsId) ;
		// Init Data fields
		entity.setMemberId( mockValues.nextString(50) ) ; // java.lang.String 
		entity.setReceiptAmount( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setReceiptProfitFrom( mockValues.nextDouble() ) ; // java.lang.Double 
		entity.setPaid( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setMonth( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setYear( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setCountpk( mockValues.nextLong() ) ; // java.lang.Long 
		entity.setPrefixcolumn( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setCreateDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setModifiedDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setUserId( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setStatus( mockValues.nextString(100) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setTblReceiptMaster( TODO ) ; // TblReceiptMaster 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TblRtgsPaidDetailsEntity> createList(int count) {
		List<TblRtgsPaidDetailsEntity> list = new LinkedList<TblRtgsPaidDetailsEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
