
/*
 * Created on 29 Feb 2016 ( Time 17:46:08 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.mock;

import java.util.LinkedList;
import java.util.List;

import com.ridas.bean.jpa.TblUserRoleMasterEntity;
import com.ridas.mock.tool.MockValues;

public class TblUserRoleMasterEntityMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public TblUserRoleMasterEntity createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(100) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public TblUserRoleMasterEntity createInstance( String userRoleId ) {
		TblUserRoleMasterEntity entity = new TblUserRoleMasterEntity();
		// Init Primary Key fields
		entity.setUserRoleId( userRoleId) ;
		// Init Data fields
		entity.setUserRoleName( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setUserRoleModuleName( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setStatus( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setUserId( mockValues.nextString(100) ) ; // java.lang.String 
		entity.setCreateDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setModifiedDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setPrefixcolumn( mockValues.nextString(500) ) ; // java.lang.String 
		entity.setCountpk( mockValues.nextLong() ) ; // java.lang.Long 
		// Init Link fields (if any)
		// setListOfTblUserRoleDetails( TODO ) ; // List<TblUserRoleDetails> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<TblUserRoleMasterEntity> createList(int count) {
		List<TblUserRoleMasterEntity> list = new LinkedList<TblUserRoleMasterEntity>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
