/*
 * Created on 29 Feb 2016 ( Time 17:45:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
//done as on 2 feb 2016
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.multipart.support.DefaultMultipartHttpServletRequest;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

import com.ridas.bean.TblMembershipForm;
import com.ridas.bean.TblPlotMaster;
//--- Entities
import com.ridas.bean.TblPlotRecMaster;
import com.ridas.bean.TblReceiptMaster;
import com.ridas.business.service.TblMembershipFormService;
import com.ridas.business.service.TblPlotMasterService;
//--- Services 
import com.ridas.business.service.TblPlotRecMasterService;
import com.ridas.business.service.TblReceiptMasterService;
//--- Common classes
import com.ridas.web.common.AbstractController;
import com.ridas.web.common.FormMode;
import com.ridas.web.common.Message;
import com.ridas.web.common.MessageType;
import com.ridas.web.listitem.TblMembershipFormListItem;
import com.ridas.web.listitem.TblPlotMasterListItem;
//--- List Items 
import com.ridas.web.listitem.TblReceiptMasterListItem;

/**
 * Spring MVC controller for 'TblPlotRecMaster' management.
 */
@Controller
@RequestMapping("/tblPlotRecMaster")
public class TblPlotRecMasterController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "tblPlotRecMaster";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "tblPlotRecMaster/form";
	private static final String JSP_LIST   = "tblPlotRecMaster/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/tblPlotRecMaster/create";
	private static final String SAVE_ACTION_UPDATE   = "/tblPlotRecMaster/update";

	//--done as on 19 feb 2016 to import CSV FILE Logic
	private static final String XLS_ACTION_UPLOAD = "fileImportAction";
	private static final String XLS_ACTION_UPLOAD_URL = "/tblPlotRecMaster/csvimport";
	private static final String JSP_SHOW_IMPORT_PAGE = "tblPlotRecMaster/fileimport";
	
	
	//--- Main entity service
	@Resource
    private TblPlotRecMasterService tblPlotRecMasterService; // Injected by Spring
	//--- Other service(s)
	@Resource
    private TblReceiptMasterService tblReceiptMasterService;
	
	@Resource
    private TblMembershipFormService tblMembershipFormService; 
	// Injected by Spring
	@Resource
    private TblPlotMasterService tblPlotMasterService; // Injected by Spring

	//done as on 2 feb 2016
	static final String folderName="TblPlotRecMaster";
	private MultipartFile file2=null;
//done as on 19 feb 2016 added logic for csv file import
	private MultipartFile fileimport2 = null;
	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public TblPlotRecMasterController() {
		super(TblPlotRecMasterController.class, MAIN_ENTITY_NAME );
		log("TblPlotRecMasterController created.");
	}

	//--------------------------------------------------------------------------------------
		// Spring MVC model management
		//--------------------------------------------------------------------------------------
		/**
		 * Populates the combo-box "items" for the referenced entity "TblMembershipForm"
		 * @param model
		 */
		private void populateListOfTblMembershipFormItems(Model model) {
			List<TblMembershipForm> list = tblMembershipFormService.findAllWhereClause();
			System.out.println("list"+list.toString());
			List<TblMembershipFormListItem> items = new LinkedList<TblMembershipFormListItem>();
			for ( TblMembershipForm tblMembershipForm : list ) {
				items.add(new TblMembershipFormListItem( tblMembershipForm ) );
			}
			model.addAttribute("listOfTblMembershipFormItems", items ) ;
		}

	
	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "TblReceiptMaster"
	 * @param model
	 */
	private void populateListOfTblReceiptMasterItems(Model model) {
		List<TblReceiptMaster> list = tblReceiptMasterService.findAll();
		List<TblReceiptMasterListItem> items = new LinkedList<TblReceiptMasterListItem>();
		for ( TblReceiptMaster tblReceiptMaster : list ) {
			items.add(new TblReceiptMasterListItem( tblReceiptMaster ) );
		}
		model.addAttribute("listOfTblReceiptMasterItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "TblPlotMaster"
	 * @param model
	 */
	private void populateListOfTblPlotMasterItems(Model model) {
		List<TblPlotMaster> list = tblPlotMasterService.findAll();
		List<TblPlotMasterListItem> items = new LinkedList<TblPlotMasterListItem>();
		for ( TblPlotMaster tblPlotMaster : list ) {
			items.add(new TblPlotMasterListItem( tblPlotMaster ) );
		}
		model.addAttribute("listOfTblPlotMasterItems", items ) ;
	}

	

	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param tblPlotRecMaster
	 */
	private void populateModel(Model model, TblPlotRecMaster tblPlotRecMaster, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, tblPlotRecMaster);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfTblReceiptMasterItems(model);
			populateListOfTblMembershipFormItems(model);
			populateListOfTblPlotMasterItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
			populateListOfTblReceiptMasterItems(model);
			populateListOfTblMembershipFormItems(model);
			populateListOfTblPlotMasterItems(model);
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of TblPlotRecMaster found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<TblPlotRecMaster> list = tblPlotRecMasterService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new TblPlotRecMaster
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		TblPlotRecMaster tblPlotRecMaster = new TblPlotRecMaster();	

// done as on 10 feb 2016  save primary key default to temp
				java.lang.Integer DUMMY=new java.lang.Integer(0+"");
		tblPlotRecMaster.setPlotReceiptId(DUMMY);

		populateModel( model, tblPlotRecMaster, FormMode.CREATE);


		//done as on 2 feb 2016
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing TblPlotRecMaster
	 * @param model Spring MVC model
	 * @param plotReceiptId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{plotReceiptId}")
	public String formForUpdate(Model model, @PathVariable("plotReceiptId") Integer plotReceiptId ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		TblPlotRecMaster tblPlotRecMaster = tblPlotRecMasterService.findById(plotReceiptId);
		System.out.println("List : "+tblPlotRecMaster.getPlotNoList().toString());
		populateModel( model, tblPlotRecMaster, FormMode.UPDATE);	
		model.addAttribute("isreport", "true");
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param tblPlotRecMaster  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid TblPlotRecMaster tblPlotRecMaster, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest,HttpServletResponse httpServletResponse) {
		//done as on 2 feb 2016
		//ADD PARAMS HttpServletResponse httpServletResponse

		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {

				

// done as on 06 feb 2016  save primary key default to temp
				java.lang.Integer DUMMY=new java.lang.Integer(0+"");

				tblPlotRecMaster.setPlotReceiptId(DUMMY);

				TblPlotRecMaster tblPlotRecMasterCreated = tblPlotRecMasterService.create(tblPlotRecMaster); 
				model.addAttribute(MAIN_ENTITY_NAME, tblPlotRecMasterCreated);

				model.addAttribute("isreport", "true");
				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				// done as on 06 feb 2016  introduced a new getter for getting the primary key of the newly created Bean coming after saved.
				return redirectToForm(httpServletRequest, tblPlotRecMasterCreated.getPlotReceiptId() );
				//return redirectToForm(httpServletRequest, tblPlotRecMaster.getPlotReceiptId() );
			} else {
				populateModel( model, tblPlotRecMaster, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "tblPlotRecMaster.error.create", e);
			populateModel( model, tblPlotRecMaster, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param tblPlotRecMaster  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid TblPlotRecMaster tblPlotRecMaster, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest,HttpServletResponse httpServletResponse) {
	//done as on 2 feb 2016
	//ADD PARAMS HttpServletResponse httpServletResponse
		
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {

				
				//--- Perform database operations
				TblPlotRecMaster tblPlotRecMasterSaved = tblPlotRecMasterService.update(tblPlotRecMaster);
				model.addAttribute(MAIN_ENTITY_NAME, tblPlotRecMasterSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, tblPlotRecMaster.getPlotReceiptId());
			
				
				
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, tblPlotRecMaster, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "tblPlotRecMaster.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, tblPlotRecMaster, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param plotReceiptId  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{plotReceiptId}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("plotReceiptId") Integer plotReceiptId) {
		log("Action 'delete'" );
		try {
			tblPlotRecMasterService.delete( plotReceiptId );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "tblPlotRecMaster.error.delete", e);
		}
		return redirectToList();
	}

	@RequestMapping("/formforcsvimport2")
	public String formForExcelImport(Model model) {
		log("Action 'formforexcelimport'");
		// --- Populates the model with a new instance
		TblPlotRecMaster tblPlotRecMaster = new TblPlotRecMaster();

		// done as on 19 feb 2016  save primary key default to temp
				java.lang.Integer DUMMY=new java.lang.Integer(0+"");

		tblPlotRecMaster.setPlotReceiptId(DUMMY);


		model.addAttribute("fileimport2", fileimport2);
		 
		model.addAttribute(XLS_ACTION_UPLOAD, XLS_ACTION_UPLOAD_URL);

		// done as on 2 feb 2016
		return JSP_SHOW_IMPORT_PAGE;
	}

	@RequestMapping("/csvimport")
	public String excelimport(TblPlotRecMaster tblPlotRecMaster, BindingResult bindingResult, Model model,
			RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest,
			HttpServletResponse httpServletResponse) {
		 
		log("Action 'csvuploading'");
		try {
			if (!bindingResult.hasErrors()) {

				 
				file2 = (MultipartFile) ((DefaultMultipartHttpServletRequest) httpServletRequest).getFile("fileimport2");
				if (file2.isEmpty() == false) {
 					String productPdfFileName = file2.getOriginalFilename();
					 
 					String contenttype = file2.getContentType();
 					
 					tblPlotRecMasterService.doImportExcelSpreadSheet(file2);	
 
				}
			}
		} catch (Exception e) {
			log("Action 'CSVImport' : Exception - " + e.getMessage());
			messageHelper.addException(model, "tblPlotRecMaster.error.create", e);	
		}
		return "redirect:/"+MAIN_ENTITY_NAME;
	}
	
	 @RequestMapping("/formforpdfreport")
	 public String formForPDReport(Model model) {
	  

	  
	  log("Action 'list'");
	  List<TblPlotRecMaster> list = tblPlotRecMasterService.findAll();
	  model.addAttribute(MAIN_LIST_NAME, list);  
	    
	  return "tblPlotRecMaster/report";
	  

	 }
}
