/*
 * Created on 29 Feb 2016 ( Time 17:45:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;
import java.util.List;

public class TblPlotRecMaster implements Serializable {

	private static final long serialVersionUID = 1L;

	// ----------------------------------------------------------------------
	// ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
	// ----------------------------------------------------------------------
	@NotNull
	private Integer plotReceiptId;

	// ----------------------------------------------------------------------
	// ENTITY DATA FIELDS
	// ----------------------------------------------------------------------
	@Size(max = 50)
	private String receiptPk;

	private Integer plotPk;

	private Long countpk;

	@Size(max = 100)
	private String prefixcolumn;

	private Date createDate;

	private Date modifiedDate;

	@Size(max = 100)
	private String status;

	@Size(max = 100)
	private String userId;

	private String memberId;
	
	private String memberName;
	
	private String plotNo;
	
	private TblReceiptMaster tblReceiptMaster;

	private TblPlotMaster tblPlotMaster;

	private TblMembershipForm tblMembershipForm;
	
	private List<TblPlotMaster> plotNoList;
	// ----------------------------------------------------------------------
	// GETTER & SETTER FOR THE KEY FIELD
	// ----------------------------------------------------------------------
	public void setPlotReceiptId(Integer plotReceiptId) {
		this.plotReceiptId = plotReceiptId;
	}

	public Integer getPlotReceiptId() {
		return this.plotReceiptId;
	}

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR FIELDS
	// ----------------------------------------------------------------------
	public void setReceiptPk(String receiptPk) {
		this.receiptPk = receiptPk;
	}

	public String getReceiptPk() {
		return this.receiptPk;
	}

	public void setPlotPk(Integer plotPk) {
		this.plotPk = plotPk;
	}

	public Integer getPlotPk() {
		return this.plotPk;
	}

	public void setCountpk(Long countpk) {
		this.countpk = countpk;
	}

	public Long getCountpk() {
		return this.countpk;
	}

	public void setPrefixcolumn(String prefixcolumn) {
		this.prefixcolumn = prefixcolumn;
	}

	public String getPrefixcolumn() {
		return this.prefixcolumn;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getStatus() {
		return this.status;
	}

	public void setUserId(String userId) {
		this.userId = userId;
	}

	public String getUserId() {
		return this.userId;
	}

	// ----------------------------------------------------------------------
	// toString METHOD
	// ----------------------------------------------------------------------

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(plotReceiptId);
		sb.append("|");
		sb.append(receiptPk);
		sb.append("|");
		sb.append(plotPk);
		sb.append("|");
		sb.append(countpk);
		sb.append("|");
		sb.append(prefixcolumn);
		sb.append("|");
		sb.append(createDate);
		sb.append("|");
		sb.append(modifiedDate);
		sb.append("|");
		sb.append(status);
		sb.append("|");
		sb.append(userId);
		return sb.toString();
	}

	public TblReceiptMaster getTblReceiptMaster() {
		return tblReceiptMaster;
	}

	public void setTblReceiptMaster(TblReceiptMaster tblReceiptMaster) {
		this.tblReceiptMaster = tblReceiptMaster;
	}

	public TblPlotMaster getTblPlotMaster() {
		return tblPlotMaster;
	}

	public void setTblPlotMaster(TblPlotMaster tblPlotMaster) {
		this.tblPlotMaster = tblPlotMaster;
	}

	public TblMembershipForm getTblMembershipForm() {
		return tblMembershipForm;
	}

	public void setTblMembershipForm(TblMembershipForm tblMembershipForm) {
		this.tblMembershipForm = tblMembershipForm;
	}

	public String getMemberId() {
		return memberId;
	}

	public void setMemberId(String memberId) {
		this.memberId = memberId;
	}

	public String getMemberName() {
		return memberName;
	}

	public void setMemberName(String memberName) {
		this.memberName = memberName;
	}

	public String getPlotNo() {
		return plotNo;
	}

	public void setPlotNo(String plotNo) {
		this.plotNo = plotNo;
	}

	public List<TblPlotMaster> getPlotNoList() {
		return plotNoList;
	}

	public void setPlotNoList(List<TblPlotMaster> plotNoList) {
		this.plotNoList = plotNoList;
	}

	

}
