/*
 * Created on 29 Feb 2016 ( Time 17:45:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class TblReceiptMaster implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 50 )
    private String receiptPk;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 50 )
    private String memberId;


    private Double receiptAmount;

    @Size( max = 100 )
    private String receiptModeofpayment;

    @Size( max = 500 )
    private String receiptAmountinwords;

    @Size( max = 255 )
    private String receiptOtherdetails;


    private Date receiptCurrentdate;

    @Size( max = 500 )
    private String receiptType;

    @Size( max = 50 )
    private String receiptBank;


    private Date receiptChequedate;

    @Size( max = 50 )
    private String receiptDrawnon;

    @Size( max = 500 )
    private String receiptBranch;

    @Size( max = 100 )
    private String receiptCity;

    @Size( max = 100 )
    private String receiptAtproject;

    @Size( max = 50 )
    private String receiptPlace;


    private Double receiptProfitFrom;


    private Double receiptProfitTo;

    @Size( max = 100 )
    private String receiptSecurityChequeNo;


    private Date receiptSecurityChequeDate;

    @Size( max = 1000 )
    private String receiptSecurityChequeDrawnon;

    @Size( max = 1000 )
    private String receiptSecurityChequeAddress;

    private Date receiptNeftDateApplicable;

    @Size( max = 100 )
    private String receiptNeftDay;

    private Long countpk;

    @Size( max = 100 )
    private String prefixcolumn;


    private Date createDate;


    private Date modifiedDate;

    @Size( max = 100 )
    private String status;

    @Size( max = 100 )
    private String userId;

    private String memberName;

    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setReceiptPk( String receiptPk ) {
        this.receiptPk = receiptPk ;
    }

    public String getReceiptPk() {
        return this.receiptPk;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setMemberId( String memberId ) {
        this.memberId = memberId;
    }
    public String getMemberId() {
        return this.memberId;
    }

    public void setReceiptAmount( Double receiptAmount ) {
        this.receiptAmount = receiptAmount;
    }
    public Double getReceiptAmount() {
        return this.receiptAmount;
    }

    public void setReceiptModeofpayment( String receiptModeofpayment ) {
        this.receiptModeofpayment = receiptModeofpayment;
    }
    public String getReceiptModeofpayment() {
        return this.receiptModeofpayment;
    }

    public void setReceiptAmountinwords( String receiptAmountinwords ) {
        this.receiptAmountinwords = receiptAmountinwords;
    }
    public String getReceiptAmountinwords() {
        return this.receiptAmountinwords;
    }

    public void setReceiptOtherdetails( String receiptOtherdetails ) {
        this.receiptOtherdetails = receiptOtherdetails;
    }
    public String getReceiptOtherdetails() {
        return this.receiptOtherdetails;
    }

    public void setReceiptCurrentdate( Date receiptCurrentdate ) {
        this.receiptCurrentdate = receiptCurrentdate;
    }
    public Date getReceiptCurrentdate() {
        return this.receiptCurrentdate;
    }

    public void setReceiptType( String receiptType ) {
        this.receiptType = receiptType;
    }
    public String getReceiptType() {
        return this.receiptType;
    }

    public void setReceiptBank( String receiptBank ) {
        this.receiptBank = receiptBank;
    }
    public String getReceiptBank() {
        return this.receiptBank;
    }

    public void setReceiptChequedate( Date receiptChequedate ) {
        this.receiptChequedate = receiptChequedate;
    }
    public Date getReceiptChequedate() {
        return this.receiptChequedate;
    }

    public void setReceiptDrawnon( String receiptDrawnon ) {
        this.receiptDrawnon = receiptDrawnon;
    }
    public String getReceiptDrawnon() {
        return this.receiptDrawnon;
    }

    public void setReceiptBranch( String receiptBranch ) {
        this.receiptBranch = receiptBranch;
    }
    public String getReceiptBranch() {
        return this.receiptBranch;
    }

    public void setReceiptCity( String receiptCity ) {
        this.receiptCity = receiptCity;
    }
    public String getReceiptCity() {
        return this.receiptCity;
    }

    public void setReceiptAtproject( String receiptAtproject ) {
        this.receiptAtproject = receiptAtproject;
    }
    public String getReceiptAtproject() {
        return this.receiptAtproject;
    }

    public void setReceiptPlace( String receiptPlace ) {
        this.receiptPlace = receiptPlace;
    }
    public String getReceiptPlace() {
        return this.receiptPlace;
    }

    public void setReceiptProfitFrom( Double receiptProfitFrom ) {
        this.receiptProfitFrom = receiptProfitFrom;
    }
    public Double getReceiptProfitFrom() {
        return this.receiptProfitFrom;
    }

    public void setReceiptProfitTo( Double receiptProfitTo ) {
        this.receiptProfitTo = receiptProfitTo;
    }
    public Double getReceiptProfitTo() {
        return this.receiptProfitTo;
    }

    public void setReceiptSecurityChequeNo( String receiptSecurityChequeNo ) {
        this.receiptSecurityChequeNo = receiptSecurityChequeNo;
    }
    public String getReceiptSecurityChequeNo() {
        return this.receiptSecurityChequeNo;
    }

    public void setReceiptSecurityChequeDate( Date receiptSecurityChequeDate ) {
        this.receiptSecurityChequeDate = receiptSecurityChequeDate;
    }
    public Date getReceiptSecurityChequeDate() {
        return this.receiptSecurityChequeDate;
    }

    public void setReceiptSecurityChequeDrawnon( String receiptSecurityChequeDrawnon ) {
        this.receiptSecurityChequeDrawnon = receiptSecurityChequeDrawnon;
    }
    public String getReceiptSecurityChequeDrawnon() {
        return this.receiptSecurityChequeDrawnon;
    }

    public void setReceiptSecurityChequeAddress( String receiptSecurityChequeAddress ) {
        this.receiptSecurityChequeAddress = receiptSecurityChequeAddress;
    }
    public String getReceiptSecurityChequeAddress() {
        return this.receiptSecurityChequeAddress;
    }
    public void setReceiptNeftDateApplicable( Date receiptNeftDateApplicable ) {
        this.receiptNeftDateApplicable = receiptNeftDateApplicable;
    }
    public Date getReceiptNeftDateApplicable() {
        return this.receiptNeftDateApplicable;
    }

    public void setReceiptNeftDay( String receiptNeftDay ) {
        this.receiptNeftDay = receiptNeftDay;
    }
    public String getReceiptNeftDay() {
        return this.receiptNeftDay;
    }

    public void setCountpk( Long countpk ) {
        this.countpk = countpk;
    }
    public Long getCountpk() {
        return this.countpk;
    }

    public void setPrefixcolumn( String prefixcolumn ) {
        this.prefixcolumn = prefixcolumn;
    }
    public String getPrefixcolumn() {
        return this.prefixcolumn;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(receiptPk);
        sb.append("|");
        sb.append(memberId);
        sb.append("|");
        sb.append(receiptAmount);
        sb.append("|");
        sb.append(receiptModeofpayment);
        sb.append("|");
        sb.append(receiptAmountinwords);
        sb.append("|");
        sb.append(receiptOtherdetails);
        sb.append("|");
        sb.append(receiptCurrentdate);
        sb.append("|");
        sb.append(receiptType);
        sb.append("|");
        sb.append(receiptBank);
        sb.append("|");
        sb.append(receiptChequedate);
        sb.append("|");
        sb.append(receiptDrawnon);
        sb.append("|");
        sb.append(receiptBranch);
        sb.append("|");
        sb.append(receiptCity);
        sb.append("|");
        sb.append(receiptAtproject);
        sb.append("|");
        sb.append(receiptPlace);
        sb.append("|");
        sb.append(receiptProfitFrom);
        sb.append("|");
        sb.append(receiptProfitTo);
        sb.append("|");
        sb.append(receiptSecurityChequeNo);
        sb.append("|");
        sb.append(receiptSecurityChequeDate);
        sb.append("|");
        sb.append(receiptSecurityChequeDrawnon);
        sb.append("|");
        sb.append(receiptSecurityChequeAddress);
        sb.append("|");
        sb.append(receiptNeftDateApplicable);
        sb.append("|");
        sb.append(receiptNeftDay);
        sb.append("|");
        sb.append(countpk);
        sb.append("|");
        sb.append(prefixcolumn);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(modifiedDate);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(userId);
        return sb.toString(); 
    }

		public String getMemberName() {
			return memberName;
		}

		public void setMemberName(String memberName) {
			this.memberName = memberName;
		} 


}
