/*
 * Created on 29 Feb 2016 ( Time 17:45:57 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.bean;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class TblUserRoleDetails implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 100 )
    private String userRoleDetailId;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Size( max = 100 )
    private String userRoleDetailName;

    @Size( max = 100 )
    private String userRoleId;

    @Size( max = 100 )
    private String status;

    @Size( max = 100 )
    private String userId;


    private Date createDate;


    private Date modifiedDate;

    @Size( max = 100 )
    private String userRoleUserId;

    @Size( max = 500 )
    private String prefixcolumn;


    private Long countpk;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUserRoleDetailId( String userRoleDetailId ) {
        this.userRoleDetailId = userRoleDetailId ;
    }

    public String getUserRoleDetailId() {
        return this.userRoleDetailId;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setUserRoleDetailName( String userRoleDetailName ) {
        this.userRoleDetailName = userRoleDetailName;
    }
    public String getUserRoleDetailName() {
        return this.userRoleDetailName;
    }

    public void setUserRoleId( String userRoleId ) {
        this.userRoleId = userRoleId;
    }
    public String getUserRoleId() {
        return this.userRoleId;
    }

    public void setStatus( String status ) {
        this.status = status;
    }
    public String getStatus() {
        return this.status;
    }

    public void setUserId( String userId ) {
        this.userId = userId;
    }
    public String getUserId() {
        return this.userId;
    }

    public void setCreateDate( Date createDate ) {
        this.createDate = createDate;
    }
    public Date getCreateDate() {
        return this.createDate;
    }

    public void setModifiedDate( Date modifiedDate ) {
        this.modifiedDate = modifiedDate;
    }
    public Date getModifiedDate() {
        return this.modifiedDate;
    }

    public void setUserRoleUserId( String userRoleUserId ) {
        this.userRoleUserId = userRoleUserId;
    }
    public String getUserRoleUserId() {
        return this.userRoleUserId;
    }

    public void setPrefixcolumn( String prefixcolumn ) {
        this.prefixcolumn = prefixcolumn;
    }
    public String getPrefixcolumn() {
        return this.prefixcolumn;
    }

    public void setCountpk( Long countpk ) {
        this.countpk = countpk;
    }
    public Long getCountpk() {
        return this.countpk;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(userRoleDetailId);
        sb.append("|");
        sb.append(userRoleDetailName);
        sb.append("|");
        sb.append(userRoleId);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(createDate);
        sb.append("|");
        sb.append(modifiedDate);
        sb.append("|");
        sb.append(userRoleUserId);
        sb.append("|");
        sb.append(prefixcolumn);
        sb.append("|");
        sb.append(countpk);
        return sb.toString(); 
    } 


}
