/*
 * Created on 29 Feb 2016 ( Time 17:45:56 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.ridas.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.ridas.bean.TblPlotMaster;
import com.ridas.business.service.TblPlotMasterService;
import com.ridas.web.listitem.TblPlotMasterListItem;

/**
 * Spring MVC controller for 'TblPlotMaster' management.
 */
@Controller
public class TblPlotMasterRestController {

	@Resource
	private TblPlotMasterService tblPlotMasterService;
	
	@RequestMapping( value="/items/tblPlotMaster",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TblPlotMasterListItem> findAllAsListItems() {
		List<TblPlotMaster> list = tblPlotMasterService.findAll();
		List<TblPlotMasterListItem> items = new LinkedList<TblPlotMasterListItem>();
		for ( TblPlotMaster tblPlotMaster : list ) {
			items.add(new TblPlotMasterListItem( tblPlotMaster ) );
		}
		return items;
	}
	
	@RequestMapping( value="/tblPlotMaster",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<TblPlotMaster> findAll() {
		return tblPlotMasterService.findAll();
	}

	@RequestMapping( value="/tblPlotMaster/{plotPk}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TblPlotMaster findOne(@PathVariable("plotPk") Integer plotPk) {
		return tblPlotMasterService.findById(plotPk);
	}
	
	@RequestMapping( value="/tblPlotMaster",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TblPlotMaster create(@RequestBody TblPlotMaster tblPlotMaster) {
		return tblPlotMasterService.create(tblPlotMaster);
	}

	@RequestMapping( value="/tblPlotMaster/{plotPk}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public TblPlotMaster update(@PathVariable("plotPk") Integer plotPk, @RequestBody TblPlotMaster tblPlotMaster) {
		return tblPlotMasterService.update(tblPlotMaster);
	}

	@RequestMapping( value="/tblPlotMaster/{plotPk}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("plotPk") Integer plotPk) {
		tblPlotMasterService.delete(plotPk);
	}
	
}
